# Generated file. Do not edit manually.
false = False
true = True
null = None

COMMANDS = {
    "ipcwatcher": {
        "bin_path": "ipc/ipcwatcher/bin/ipcwatcher",
        "description": "a tool for tracing IPC like unix domain socket and shared memory",
        "options": [
            "-u",
            "--uds",
            "-m",
            "--mmap",
            "-p",
            "--pid",
            "--filterPath",
            "--traceNoAnonUds",
            "--payload",
            "--force",
            "--pcapFile",
            "--fromJson",
            "--vvv",
            "--verbose",
            "-v",
            "--version",
            "-h",
            "--help"
        ]
    },
    "netwatcher": {
        "bin_path": "net/netwatcher/bin/netwatcher",
        "description": "a tool for tracing TCP/IP stack events",
        "options": [
            "-a",
            "--all",
            "-e",
            "--err",
            "-x",
            "--extra",
            "-r",
            "--retrans",
            "-t",
            "--time",
            "-i",
            "--http",
            "-s",
            "--sport",
            "-d",
            "--dport",
            "-u",
            "--udp",
            "-n",
            "--net_filter",
            "-k",
            "--drop_reason",
            "-F",
            "--addr_to_func",
            "-I",
            "--icmptime",
            "-S",
            "--tcpstate",
            "-L",
            "--timeload",
            "-D",
            "--dns",
            "-A",
            "--stack",
            "-C",
            "--count",
            "-T",
            "--rtt",
            "-U",
            "--rst_counters",
            "-h",
            "--help"
        ]
    },
    "tcprtt": {
        "bin_path": "net/tcprtt/bin/tcprtt",
        "description": "Summarize TCP RTT as a histogram",
        "options": [
            "-i",
            "--interval",
            "-d",
            "--duration",
            "-T",
            "--timestamp",
            "-m",
            "--millisecond",
            "-p",
            "--lport",
            "-P",
            "--rport",
            "-a",
            "--laddr",
            "-A",
            "--raddr",
            "-b",
            "--byladdr",
            "-B",
            "--byraddr",
            "-e",
            "--extension",
            "-v",
            "--verbose",
            "-h",
            "--help"
        ]
    },
    "tcpaccd": {
        "bin_path": "net/tcpaccd/bin/tcpaccd",
        "description": "a daemon for accerate TCP in IPC",
        "options": [
            "-h",
            "--help",
            "-c",
            "--cgroup",
            "-v",
            "--version",
            "-V",
            "--verbose"
        ]
    },
    "tcpconnect": {
        "bin_path": "net/tcpconnect/bin/tcpconnect",
        "description": "Count/Trace active tcp connections",
        "options": [
            "-v",
            "--verbose",
            "-t",
            "--timestamp",
            "-c",
            "--count",
            "-U",
            "--print-uid",
            "-p",
            "--pid",
            "-u",
            "--uid",
            "-s",
            "--source-port",
            "-P",
            "--port",
            "-h",
            "--help"
        ]
    },
    "nettrace": {
        "bin_path": "net/nettrace/bin/nettrace",
        "description": "a tool to trace skb in kernel and diagnose network problem",
        "options": [
            "-s",
            "--saddr",
            "-d",
            "--daddr",
            "--addr",
            "-p",
            "-D",
            "--dport",
            "-S",
            "--sport",
            "-P",
            "--port",
            "--netns",
            "--netns-current",
            "--pid",
            "--min-latency",
            "--pkt-len",
            "--tcp-flags",
            "--pkt-len",
            "--tcp-rtt",
            "--tcp--srtt",
            "--basic",
            "--diag",
            "--diag-quiet",
            "--diag-keep",
            "--drop",
            "--drop-stack",
            "--sock",
            "--monitor",
            "--rtt",
            "--rtt-detail",
            "--filter-srtt",
            "--filter-minrtt",
            "--latency-show",
            "--latency-free",
            "--latency",
            "--latency-summary",
            "-t",
            "--trace",
            "--force",
            "--ret",
            "--detail",
            "--date",
            "-c",
            "--count",
            "--hooks",
            "--tiny-show",
            "--trace-stack",
            "--trace-matcher",
            "--trace-noclone",
            "--func-stats",
            "--rate-limit",
            "--btf-path",
            "-v",
            "--debug",
            "-h",
            "--help",
            "-V",
            "--version"
        ]
    },
    "gethostlatency": {
        "bin_path": "net/gethostlatency/bin/gethostlatency",
        "description": "Show latency for getaddrinfo/gethostbyname[2] calls",
        "options": [
            "-p",
            "--pid",
            "-l",
            "--libc",
            "-vvv",
            "--verbose",
            "-h",
            "--help",
            "-v",
            "--version"
        ]
    },
    "solisten": {
        "bin_path": "net/solisten/bin/solisten",
        "description": "Trace IPv4 and IPv6 listen syscalls",
        "options": [
            "-p",
            "--pid",
            "-t",
            "--timestamp",
            "-vvv",
            "--verbose",
            "-h",
            "--help",
            "-v",
            "--version"
        ]
    },
    "bindsnoop": {
        "bin_path": "net/bindsnoop/bin/bindsnoop",
        "description": "a tool for tracing bind() syscall events",
        "options": [
            "-t",
            "--timestamp",
            "-x",
            "--failed",
            "-p",
            "--pid",
            "-P",
            "--ports",
            "-c",
            "--cgroup",
            "-v",
            "--version",
            "-vvv",
            "--verbose",
            "-h",
            "--help"
        ]
    }
}
