# Generated file. Do not edit manually.
false = False
true = True
null = None

COMMANDS = {
    "ipcwatcher": {
        "bin_path": "ipc/ipcwatcher/bin/ipcwatcher",
        "description": "a tool for tracing IPC like unix domain socket and shared memory",
        "options": [
            "-u",
            "--uds",
            "-m",
            "--mmap",
            "-p",
            "--pid",
            "--filterPath",
            "--traceNoAnonUds",
            "--payload",
            "--force",
            "--pcapFile",
            "--fromJson",
            "--vvv",
            "--verbose",
            "-v",
            "--version",
            "-h",
            "--help"
        ]
    },
    "netwatcher": {
        "bin_path": "net/netwatcher/bin/netwatcher",
        "description": "a tool for tracing TCP/IP stack events",
        "options": [
            "-a",
            "--all",
            "-e",
            "--err",
            "-x",
            "--extra",
            "-r",
            "--retrans",
            "-t",
            "--time",
            "-i",
            "--http",
            "-s",
            "--sport",
            "-d",
            "--dport",
            "-u",
            "--udp",
            "-n",
            "--net_filter",
            "-k",
            "--drop_reason",
            "-F",
            "--addr_to_func",
            "-I",
            "--icmptime",
            "-S",
            "--tcpstate",
            "-L",
            "--timeload",
            "-D",
            "--dns",
            "-A",
            "--stack",
            "-C",
            "--count",
            "-T",
            "--rtt",
            "-U",
            "--rst_counters",
            "-h",
            "--help"
        ]
    },
    "tcpaccd": {
        "bin_path": "net/tcpaccd/bin/tcpaccd",
        "description": "a daemon for accerate TCP in IPC",
        "options": [
            "-h",
            "--help"
        ]
    },
    "nettrace": {
        "bin_path": "net/nettrace/bin/nettrace",
        "description": "a tool to trace skb in kernel and diagnose network problem",
        "options": [
            "-s",
            "--saddr",
            "-d",
            "--daddr",
            "--addr",
            "-p",
            "-D",
            "--dport",
            "-S",
            "--sport",
            "-P",
            "--port",
            "--netns",
            "--netns-current",
            "--pid",
            "--min-latency",
            "--pkt-len",
            "--tcp-flags",
            "--pkt-len",
            "--tcp-rtt",
            "--tcp--srtt",
            "--basic",
            "--diag",
            "--diag-quiet",
            "--diag-keep",
            "--drop",
            "--drop-stack",
            "--sock",
            "--monitor",
            "--rtt",
            "--rtt-detail",
            "--filter-srtt",
            "--filter-minrtt",
            "--latency-show",
            "--latency-free",
            "--latency",
            "--latency-summary",
            "-t",
            "--trace",
            "--force",
            "--ret",
            "--detail",
            "--date",
            "-c",
            "--count",
            "--hooks",
            "--tiny-show",
            "--trace-stack",
            "--trace-matcher",
            "--trace-noclone",
            "--func-stats",
            "--rate-limit",
            "--btf-path",
            "-v",
            "--debug",
            "-h",
            "--help",
            "-V",
            "--version"
        ]
    }
}
